[package]
name = "efd-to-database"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.2", features = ["time", "rt", "macros", "rt-multi-thread"] }
sqlx = { version = "0.8.5", features = ["sqlite", "macros", "runtime-tokio", "chrono"] }
chrono = { version = "0.4", features = ["serde"] }
encoding_rs = "0.8.35"
once_cell = "1.21.3"
futures = "0.3.31"
anyhow = "1.0.98"
time = {version = "0.3.41" , features = ["formatting"]}
