-- ------------------------------------------------------
-- http://github.com/josuelima/sped_schema
-- Schema SQL EFD-Contribuicoes
-- Versão 1.16 (30/06/2014)
-- SQLite version
-- ------------------------------------------------------

--
-- Registro: 0000
--
CREATE TABLE reg_0000 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_VER TEXT DEFAULT NULL,
    TIPO_ESCRIT TEXT DEFAULT NULL,
    IND_SIT_ESP TEXT DEFAULT NULL,
    NUM_REC_ANTERIOR TEXT DEFAULT NULL,
    DT_INI DATE DEFAULT NULL,
    DT_FIN DATE DEFAULT NULL,
    NOME TEXT DEFAULT NULL,
    CNPJ TEXT DEFAULT NULL,
    UF TEXT DEFAULT NULL,
    COD_MUN TEXT DEFAULT NULL,
    SUFRAMA TEXT DEFAULT NULL,
    IND_NAT_PJ TEXT DEFAULT NULL,
    IND_ATIV TEXT DEFAULT NULL
);

--
-- Registro: 0001
--
CREATE TABLE reg_0001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: 0035
--
CREATE TABLE reg_0035 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_SCP TEXT DEFAULT NULL,
    NOME_SCP TEXT DEFAULT NULL,
    INF_COMP TEXT DEFAULT NULL
);

--
-- Registro: 0100
--
CREATE TABLE reg_0100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NOME TEXT DEFAULT NULL,
    CPF TEXT DEFAULT NULL,
    CRC TEXT DEFAULT NULL,
    CNPJ TEXT DEFAULT NULL,
    CEP TEXT DEFAULT NULL,
    END TEXT DEFAULT NULL,
    NUM TEXT DEFAULT NULL,
    COMPL TEXT DEFAULT NULL,
    BAIRRO TEXT DEFAULT NULL,
    FONE TEXT DEFAULT NULL,
    FAX TEXT DEFAULT NULL,
    EMAIL TEXT DEFAULT NULL,
    COD_MUN TEXT DEFAULT NULL
);

--
-- Registro: 0110
--
CREATE TABLE reg_0110 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_INC_TRIB TEXT DEFAULT NULL,
    IND_APRO_CRED TEXT DEFAULT NULL,
    COD_TIPO_CONT TEXT DEFAULT NULL,
    IND_REG_CUM TEXT DEFAULT NULL
);

--
-- Registro: 0111
--
CREATE TABLE reg_0111 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    REC_BRU_NCUM_TRIB_MI NUMERIC DEFAULT NULL,
    REC_BRU_NCUM_NT_MI NUMERIC DEFAULT NULL,
    REC_BRU_NCUM_EXP NUMERIC DEFAULT NULL,
    REC_BRU_CUM NUMERIC DEFAULT NULL,
    REC_BRU_TOTAL NUMERIC DEFAULT NULL
);

--
-- Registro: 0120
--
CREATE TABLE reg_0120 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    MES_DISPENSA TEXT DEFAULT NULL,
    INF_COMP TEXT DEFAULT NULL
);

--
-- Registro: 0140
--
CREATE TABLE reg_0140 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_EST TEXT DEFAULT NULL,
    NOME TEXT DEFAULT NULL,
    CNPJ TEXT DEFAULT NULL,
    UF TEXT DEFAULT NULL,
    IE TEXT DEFAULT NULL,
    COD_MUN TEXT DEFAULT NULL,
    IM TEXT DEFAULT NULL,
    SUFRAMA TEXT DEFAULT NULL
);

--
-- Registro: 0145
--
CREATE TABLE reg_0145 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_INC_TRIB TEXT DEFAULT NULL,
    VL_REC_TOT NUMERIC DEFAULT NULL,
    VL_REC_ATIV NUMERIC DEFAULT NULL,
    VL_REC_DEMAIS_ATIV NUMERIC DEFAULT NULL,
    INFO_COMPL TEXT DEFAULT NULL
);

--
-- Registro: 0150
--
CREATE TABLE reg_0150 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_PART TEXT DEFAULT NULL,
    NOME TEXT DEFAULT NULL,
    COD_PAIS TEXT DEFAULT NULL,
    CNPJ TEXT DEFAULT NULL,
    CPF TEXT DEFAULT NULL,
    IE TEXT DEFAULT NULL,
    COD_MUN TEXT DEFAULT NULL,
    SUFRAMA TEXT DEFAULT NULL,
    END TEXT DEFAULT NULL,
    NUM TEXT DEFAULT NULL,
    COMPL TEXT DEFAULT NULL,
    BAIRRO TEXT DEFAULT NULL
);

--
-- Registro: 0190
--
CREATE TABLE reg_0190 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    UNID TEXT DEFAULT NULL,
    DESCR TEXT DEFAULT NULL
);

--
-- Registro: 0200
--
CREATE TABLE reg_0200 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_ITEM TEXT DEFAULT NULL,
    DESCR_ITEM TEXT DEFAULT NULL,
    COD_BARRA TEXT DEFAULT NULL,
    COD_ANT_ITEM TEXT DEFAULT NULL,
    UNID_INV TEXT DEFAULT NULL,
    TIPO_ITEM TEXT DEFAULT NULL,
    COD_NCM TEXT DEFAULT NULL,
    EX_IPI TEXT DEFAULT NULL,
    COD_GEN TEXT DEFAULT NULL,
    COD_LST TEXT DEFAULT NULL,
    ALIQ_ICMS NUMERIC DEFAULT NULL
);

--
-- Registro: 0205
--
CREATE TABLE reg_0205 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    DESCR_ANT_ITEM TEXT DEFAULT NULL,
    DT_INI DATE DEFAULT NULL,
    DT_FIM DATE DEFAULT NULL,
    COD_ANT_ITEM TEXT DEFAULT NULL
);

--
-- Registro: 0206
--
CREATE TABLE reg_0206 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_COMB TEXT DEFAULT NULL
);

--
-- Registro: 0208
--
CREATE TABLE reg_0208 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_TAB TEXT DEFAULT NULL,
    COD_GRU TEXT DEFAULT NULL,
    MARCA_COM TEXT DEFAULT NULL
);

--
-- Registro: 0400
--
CREATE TABLE reg_0400 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_NAT TEXT DEFAULT NULL,
    DESCR_NAT TEXT DEFAULT NULL
);

--
-- Registro: 0450
--
CREATE TABLE reg_0450 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_INF TEXT DEFAULT NULL,
    TXT TEXT DEFAULT NULL
);

--
-- Registro: 0500
--
CREATE TABLE reg_0500 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    DT_ALT DATE DEFAULT NULL,
    COD_NAT_CC TEXT DEFAULT NULL,
    IND_CTA TEXT DEFAULT NULL,
    NIVEL TEXT DEFAULT NULL,
    COD_CTA TEXT DEFAULT NULL,
    NOME_CTA TEXT DEFAULT NULL,
    COD_CTA_REF TEXT DEFAULT NULL,
    CNPJ_EST TEXT DEFAULT NULL
);

--
-- Registro: 0600
--
CREATE TABLE reg_0600 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    DT_ALT DATE DEFAULT NULL,
    COD_CCUS TEXT DEFAULT NULL,
    CCUS TEXT DEFAULT NULL
);

--
-- Registro: 0990
--
CREATE TABLE reg_0990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_0 TEXT DEFAULT NULL
);

--
-- Registro: 1001
--
CREATE TABLE reg_1001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: 1010
--
CREATE TABLE reg_1010 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC TEXT DEFAULT NULL,
    ID_SEC_JUD TEXT DEFAULT NULL,
    ID_VARA TEXT DEFAULT NULL,
    IND_NAT_ACAO TEXT DEFAULT NULL,
    DESC_DEC_JUD TEXT DEFAULT NULL,
    DT_SENT_JUD DATE DEFAULT NULL
);

--
-- Registro: 1020
--
CREATE TABLE reg_1020 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC TEXT DEFAULT NULL,
    IND_NAT_ACAO TEXT DEFAULT NULL,
    DT_DEC_ADM DATE DEFAULT NULL
);

--
-- Registro: 1100
--
CREATE TABLE reg_1100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    PER_APU_CRED TEXT DEFAULT NULL,
    ORIG_CRED TEXT DEFAULT NULL,
    CNPJ_SUC TEXT DEFAULT NULL,
    COD_CRED TEXT DEFAULT NULL,
    VL_CRED_APU NUMERIC DEFAULT NULL,
    VL_CRED_EXT_APU NUMERIC DEFAULT NULL,
    VL_TOT_CRED_APU NUMERIC DEFAULT NULL,
    VL_CRED_DESC_PA_ANT NUMERIC DEFAULT NULL,
    VL_CRED_PER_PA_ANT NUMERIC DEFAULT NULL,
    VL_CRED_DCOMP_PA_ANT NUMERIC DEFAULT NULL,
    SD_CRED_DISP_EFD NUMERIC DEFAULT NULL,
    VL_CRED_DESC_EFD NUMERIC DEFAULT NULL,
    VL_CRED_PER_EFD NUMERIC DEFAULT NULL,
    VL_CRED_DCOMP_EFD NUMERIC DEFAULT NULL,
    VL_CRED_TRANS NUMERIC DEFAULT NULL,
    VL_CRED_OUT NUMERIC DEFAULT NULL,
    SLD_CRED_FIM NUMERIC DEFAULT NULL
);

--
-- Registro: 1300
--
CREATE TABLE reg_1300 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_NAT_RET TEXT DEFAULT NULL,
    PR_REC_RET TEXT DEFAULT NULL,
    VL_RET_APU NUMERIC DEFAULT NULL,
    VL_RET_DED NUMERIC DEFAULT NULL,
    VL_RET_PER NUMERIC DEFAULT NULL,
    VL_RET_DCOMP NUMERIC DEFAULT NULL,
    SLD_RET NUMERIC DEFAULT NULL
);

--
-- Registro: 1500
--
CREATE TABLE reg_1500 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    PER_APU_CRED TEXT DEFAULT NULL,
    ORIG_CRED TEXT DEFAULT NULL,
    CNPJ_SUC TEXT DEFAULT NULL,
    COD_CRED TEXT DEFAULT NULL,
    VL_CRED_APU NUMERIC DEFAULT NULL,
    VL_CRED_EXT_APU NUMERIC DEFAULT NULL,
    VL_TOT_CRED_APU NUMERIC DEFAULT NULL,
    VL_CRED_DESC_PA_ANT NUMERIC DEFAULT NULL,
    VL_CRED_PER_PA_ANT NUMERIC DEFAULT NULL,
    VL_CRED_DCOMP_PA_ANT NUMERIC DEFAULT NULL,
    SD_CRED_DISP_EFD NUMERIC DEFAULT NULL,
    VL_CRED_DESC_EFD NUMERIC DEFAULT NULL,
    VL_CRED_PER_EFD NUMERIC DEFAULT NULL,
    VL_CRED_DCOMP_EFD NUMERIC DEFAULT NULL,
    VL_CRED_TRANS NUMERIC DEFAULT NULL,
    VL_CRED_OUT NUMERIC DEFAULT NULL,
    SLD_CRED_FIM NUMERIC DEFAULT NULL
);

--
-- Registro: 1700
--
CREATE TABLE reg_1700 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_NAT_RET TEXT DEFAULT NULL,
    PR_REC_RET TEXT DEFAULT NULL,
    VL_RET_APU NUMERIC DEFAULT NULL,
    VL_RET_DED NUMERIC DEFAULT NULL,
    VL_RET_PER NUMERIC DEFAULT NULL,
    VL_RET_DCOMP NUMERIC DEFAULT NULL,
    SLD_RET NUMERIC DEFAULT NULL
);

--
-- Registro: 1800
--
CREATE TABLE reg_1800 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    INC_IMOB TEXT DEFAULT NULL,
    REC_RECEB_RET NUMERIC DEFAULT NULL,
    REC_FIN_RET NUMERIC DEFAULT NULL,
    BC_RET NUMERIC DEFAULT NULL,
    ALIQ_RET NUMERIC DEFAULT NULL,
    VL_REC_UNI NUMERIC DEFAULT NULL,
    DT_REC_UNI DATE DEFAULT NULL,
    COD_REC TEXT DEFAULT NULL
);

--
-- Registro: 1900
--
CREATE TABLE reg_1900 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ TEXT DEFAULT NULL,
    COD_MOD TEXT DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB_SER TEXT DEFAULT NULL,
    COD_SIT TEXT DEFAULT NULL,
    VL_TOT_REC NUMERIC DEFAULT NULL,
    QUANT_DOC TEXT DEFAULT NULL,
    CST_PIS TEXT DEFAULT NULL,
    CST_COFINS TEXT DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    INFO_COMPL TEXT DEFAULT NULL,
    COD_CTA TEXT DEFAULT NULL
);

--
-- Registro: 1990
--
CREATE TABLE reg_1990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_1 TEXT DEFAULT NULL
);

--
-- Registro: 9001
--
CREATE TABLE reg_9001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: 9900
--
CREATE TABLE reg_9900 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    REG_BLC TEXT DEFAULT NULL,
    QTD_REG_BLC VARCHAR DEFAULT NULL
);

--
-- Registro: 9990
--
CREATE TABLE reg_9990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_9 VARCHAR DEFAULT NULL
);

--
-- Registro: 9999
--
CREATE TABLE reg_9999 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN VARCHAR DEFAULT NULL
);

--
-- Registro: a001
--
CREATE TABLE reg_a001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: a010
--
CREATE TABLE reg_a010 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL
);

--
-- Registro: a100
--
CREATE TABLE reg_a100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_OPER TEXT DEFAULT NULL,
    IND_EMIT TEXT DEFAULT NULL,
    COD_PART VARCHAR DEFAULT NULL,
    COD_SIT VARCHAR DEFAULT NULL,
    SER VARCHAR DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    CHV_NFSE VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    DT_EXE_SERV date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    IND_PGTO TEXT DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS_RET DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS_RET DECIMAL(21, 2) DEFAULT NULL,
    VL_ISS DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: a110
--
CREATE TABLE reg_a110 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_INF VARCHAR DEFAULT NULL,
    TXT_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: a111
--
CREATE TABLE reg_a111 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: a120
--
CREATE TABLE reg_a120 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_TOT_SERV DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS_IMP DECIMAL(21, 2) DEFAULT NULL,
    DT_PAG_PIS date DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS_IMP DECIMAL(21, 2) DEFAULT NULL,
    DT_PAG_COFINS date DEFAULT NULL,
    LOC_EXE_SERV TEXT DEFAULT NULL
);

--
-- Registro: a170
--
CREATE TABLE reg_a170 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_ITEM TEXT DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    DESCR_COMPL VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    IND_ORIG_CRED TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(8, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    COD_CCUS VARCHAR DEFAULT NULL
);

--
-- Registro: a990
--
CREATE TABLE reg_a990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_A VARCHAR DEFAULT NULL
);

--
-- Registro: c001
--
CREATE TABLE reg_c001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: c010
--
CREATE TABLE reg_c010 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL,
    IND_ESCRI TEXT DEFAULT NULL
);

--
-- Registro: c100
--
CREATE TABLE reg_c100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_OPER TEXT DEFAULT NULL,
    IND_EMIT TEXT DEFAULT NULL,
    COD_PART VARCHAR DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_SIT VARCHAR DEFAULT NULL,
    SER VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    CHV_NFE VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    DT_E_S date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    IND_PGTO TEXT DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_ABAT_NT DECIMAL(21, 2) DEFAULT NULL,
    VL_MERC DECIMAL(21, 2) DEFAULT NULL,
    IND_FRT TEXT DEFAULT NULL,
    VL_FRT DECIMAL(21, 2) DEFAULT NULL,
    VL_SEG DECIMAL(21, 2) DEFAULT NULL,
    VL_OUT_DA DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS_ST DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS_ST DECIMAL(21, 2) DEFAULT NULL,
    VL_IPI DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS_ST DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS_ST DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c110
--
CREATE TABLE reg_c110 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_INF VARCHAR DEFAULT NULL,
    TXT_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: c111
--
CREATE TABLE reg_c111 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: c120
--
CREATE TABLE reg_c120 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_DOC_IMP TEXT DEFAULT NULL,
    NUM_DOC_IMP VARCHAR DEFAULT NULL,
    VL_PIS_IMP DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS_IMP DECIMAL(21, 2) DEFAULT NULL,
    NUM_ACDRAW VARCHAR DEFAULT NULL
);

--
-- Registro: c170
--
CREATE TABLE reg_c170 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_ITEM VARCHAR DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    DESCR_COMPL VARCHAR DEFAULT NULL,
    QTD DECIMAL(24, 5) DEFAULT NULL,
    UNID VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL,
    CST_ICMS VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    COD_NAT VARCHAR DEFAULT NULL,
    VL_BC_ICMS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_ICMS DECIMAL(8, 2) DEFAULT NULL,
    VL_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS_ST DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_ST DECIMAL(8, 2) DEFAULT NULL,
    VL_ICMS_ST DECIMAL(21, 2) DEFAULT NULL,
    IND_APUR TEXT DEFAULT NULL,
    CST_IPI VARCHAR DEFAULT NULL,
    COD_ENQ VARCHAR DEFAULT NULL,
    VL_BC_IPI DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_IPI DECIMAL(8, 2) DEFAULT NULL,
    VL_IPI DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c180
--
CREATE TABLE reg_c180 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    DT_DOC_INI date DEFAULT NULL,
    DT_DOC_FIN date DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    COD_NCM VARCHAR DEFAULT NULL,
    EX_IPI VARCHAR DEFAULT NULL,
    VL_TOT_ITEM DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c181
--
CREATE TABLE reg_c181 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c185
--
CREATE TABLE reg_c185 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c188
--
CREATE TABLE reg_c188 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: c190
--
CREATE TABLE reg_c190 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    DT_REF_INI date DEFAULT NULL,
    DT_REF_FIN date DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    COD_NCM VARCHAR DEFAULT NULL,
    EX_IPI VARCHAR DEFAULT NULL,
    VL_TOT_ITEM DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c191
--
CREATE TABLE reg_c191 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ_CPF_PART VARCHAR DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c195
--
CREATE TABLE reg_c195 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ_CPF_PART VARCHAR DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c198
--
CREATE TABLE reg_c198 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: c199
--
CREATE TABLE reg_c199 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_DOC_IMP TEXT DEFAULT NULL,
    NUM_DOC_IMP VARCHAR DEFAULT NULL,
    VL_PIS_IMP DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS_IMP DECIMAL(21, 2) DEFAULT NULL,
    NUM_ACDRAW VARCHAR DEFAULT NULL
);

--
-- Registro: c380
--
CREATE TABLE reg_c380 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    DT_DOC_INI date DEFAULT NULL,
    DT_DOC_FIN date DEFAULT NULL,
    NUM_DOC_INI VARCHAR DEFAULT NULL,
    NUM_DOC_FIN VARCHAR DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_DOC_CANC DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c381
--
CREATE TABLE reg_c381 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c385
--
CREATE TABLE reg_c385 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c395
--
CREATE TABLE reg_c395 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_PART VARCHAR DEFAULT NULL,
    SER VARCHAR DEFAULT NULL,
    SUB_SER VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c396
--
CREATE TABLE reg_c396 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c400
--
CREATE TABLE reg_c400 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    ECF_MOD VARCHAR DEFAULT NULL,
    ECF_FAB VARCHAR DEFAULT NULL,
    ECF_CX VARCHAR DEFAULT NULL
);

--
-- Registro: c405
--
CREATE TABLE reg_c405 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    CRO VARCHAR DEFAULT NULL,
    CRZ VARCHAR DEFAULT NULL,
    NUM_COO_FIN VARCHAR DEFAULT NULL,
    GT_FIN DECIMAL(21, 2) DEFAULT NULL,
    VL_BRT DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c481
--
CREATE TABLE reg_c481 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c485
--
CREATE TABLE reg_c485 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c489
--
CREATE TABLE reg_c489 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: c490
--
CREATE TABLE reg_c490 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    DT_DOC_INI date DEFAULT NULL,
    DT_DOC_FIN date DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL
);

--
-- Registro: c491
--
CREATE TABLE reg_c491 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c495
--
CREATE TABLE reg_c495 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c499
--
CREATE TABLE reg_c499 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: c500
--
CREATE TABLE reg_c500 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_PART VARCHAR DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_SIT VARCHAR DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    DT_E_S date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS DECIMAL(21, 2) DEFAULT NULL,
    COD_INF VARCHAR DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c501
--
CREATE TABLE reg_c501 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c505
--
CREATE TABLE reg_c505 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c509
--
CREATE TABLE reg_c509 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: c600
--
CREATE TABLE reg_c600 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_MUN VARCHAR DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    COD_CONS VARCHAR DEFAULT NULL,
    QTD_CONS VARCHAR DEFAULT NULL,
    QTD_CANC VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    CONS VARCHAR DEFAULT NULL,
    VL_FORN DECIMAL(21, 2) DEFAULT NULL,
    VL_SERV_NT DECIMAL(21, 2) DEFAULT NULL,
    VL_TERC DECIMAL(21, 2) DEFAULT NULL,
    VL_DA DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS_ST DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS_ST DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: c601
--
CREATE TABLE reg_c601 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c605
--
CREATE TABLE reg_c605 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: c609
--
CREATE TABLE reg_c609 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: c990
--
CREATE TABLE reg_c990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_C VARCHAR DEFAULT NULL
);

--
-- Registro: d001
--
CREATE TABLE reg_d001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: d010
--
CREATE TABLE reg_d010 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL
);

--
-- Registro: d100
--
CREATE TABLE reg_d100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_OPER TEXT DEFAULT NULL,
    IND_EMIT TEXT DEFAULT NULL,
    COD_PART VARCHAR DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_SIT VARCHAR DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    CHV_CTE VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    DT_A_P date DEFAULT NULL,
    TP_CTE TEXT DEFAULT NULL,
    CHV_CTE_REF VARCHAR DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    IND_FRT TEXT DEFAULT NULL,
    VL_SERV DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_NT DECIMAL(21, 2) DEFAULT NULL,
    COD_INF VARCHAR DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d101
--
CREATE TABLE reg_d101 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_NAT_FRT TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d105
--
CREATE TABLE reg_d105 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_NAT_FRT TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d111
--
CREATE TABLE reg_d111 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: d200
--
CREATE TABLE reg_d200 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_SIT VARCHAR DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    NUM_DOC_INI VARCHAR DEFAULT NULL,
    NUM_DOC_FIN VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    DT_REF date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: d201
--
CREATE TABLE reg_d201 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d205
--
CREATE TABLE reg_d205 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d209
--
CREATE TABLE reg_d209 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: d300
--
CREATE TABLE reg_d300 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    NUM_DOC_INI VARCHAR DEFAULT NULL,
    NUM_DOC_FIN VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    DT_REF date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d309
--
CREATE TABLE reg_d309 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: d350
--
CREATE TABLE reg_d350 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    ECF_MOD VARCHAR DEFAULT NULL,
    ECF_FAB VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    CRO VARCHAR DEFAULT NULL,
    CRZ VARCHAR DEFAULT NULL,
    NUM_COO_FIN VARCHAR DEFAULT NULL,
    GT_FIN DECIMAL(21, 2) DEFAULT NULL,
    VL_BRT DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d359
--
CREATE TABLE reg_d359 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: d500
--
CREATE TABLE reg_d500 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_OPER TEXT DEFAULT NULL,
    IND_EMIT TEXT DEFAULT NULL,
    COD_PART VARCHAR DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_SIT VARCHAR DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DT_DOC date DEFAULT NULL,
    DT_A_P date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_SERV DECIMAL(21, 2) DEFAULT NULL,
    VL_SERV_NT DECIMAL(21, 2) DEFAULT NULL,
    VL_TERC DECIMAL(21, 2) DEFAULT NULL,
    VL_DA DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS DECIMAL(21, 2) DEFAULT NULL,
    COD_INF VARCHAR DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: d501
--
CREATE TABLE reg_d501 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d505
--
CREATE TABLE reg_d505 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d509
--
CREATE TABLE reg_d509 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: d600
--
CREATE TABLE reg_d600 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    COD_MUN VARCHAR DEFAULT NULL,
    SER TEXT DEFAULT NULL,
    SUB VARCHAR DEFAULT NULL,
    IND_REC TEXT DEFAULT NULL,
    QTD_CONS VARCHAR DEFAULT NULL,
    DT_DOC_INI date DEFAULT NULL,
    DT_DOC_FIN date DEFAULT NULL,
    VL_DOC DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_SERV DECIMAL(21, 2) DEFAULT NULL,
    VL_SERV_NT DECIMAL(21, 2) DEFAULT NULL,
    VL_TERC DECIMAL(21, 2) DEFAULT NULL,
    VL_DA DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_ICMS DECIMAL(21, 2) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: d601
--
CREATE TABLE reg_d601 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CLASS TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d605
--
CREATE TABLE reg_d605 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CLASS TEXT DEFAULT NULL,
    VL_ITEM DECIMAL(21, 2) DEFAULT NULL,
    VL_DESC DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: d609
--
CREATE TABLE reg_d609 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: d990
--
CREATE TABLE reg_d990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_D VARCHAR DEFAULT NULL
);

--
-- Registro: f001
--
CREATE TABLE reg_f001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: f010
--
CREATE TABLE reg_f010 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL
);

--
-- Registro: f100
--
CREATE TABLE reg_f100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_OPER TEXT DEFAULT NULL,
    COD_PART VARCHAR DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    DT_OPER date DEFAULT NULL,
    VL_OPER DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(23, 4) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(23, 4) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    IND_ORIG_CRED TEXT DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    COD_CCUS VARCHAR DEFAULT NULL,
    DESC_DOC_OPER VARCHAR DEFAULT NULL
);

--
-- Registro: f111
--
CREATE TABLE reg_f111 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f120
--
CREATE TABLE reg_f120 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    IDENT_BEM_IMOB VARCHAR DEFAULT NULL,
    IND_ORIG_CRED TEXT DEFAULT NULL,
    IND_UTIL_BEM_IMOB TEXT DEFAULT NULL,
    VL_OPER_DEP DECIMAL(21, 2) DEFAULT NULL,
    PARC_OPER_NAO_BC_CRED DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    COD_CCUS VARCHAR DEFAULT NULL,
    DESC_BEM_IMOB VARCHAR DEFAULT NULL
);

--
-- Registro: f129
--
CREATE TABLE reg_f129 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f130
--
CREATE TABLE reg_f130 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    IDENT_BEM_IMOB VARCHAR DEFAULT NULL,
    IND_ORIG_CRED TEXT DEFAULT NULL,
    IND_UTIL_BEM_IMOB TEXT DEFAULT NULL,
    MES_OPER_AQUIS VARCHAR DEFAULT NULL,
    VL_OPER_AQUIS DECIMAL(21, 2) DEFAULT NULL,
    PARC_OPER_NAO_BC_CRED DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CRED DECIMAL(21, 2) DEFAULT NULL,
    IND_NR_PARC TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    COD_CCUS VARCHAR DEFAULT NULL,
    DESC_BEM_IMOB VARCHAR DEFAULT NULL
);

--
-- Registro: f139
--
CREATE TABLE reg_f139 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f150
--
CREATE TABLE reg_f150 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    VL_TOT_EST DECIMAL(21, 2) DEFAULT NULL,
    EST_IMP DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_EST DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_MEN_EST DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_CRED_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_CRED_COFINS DECIMAL(21, 2) DEFAULT NULL,
    DESC_EST VARCHAR DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: f200
--
CREATE TABLE reg_f200 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_OPER VARCHAR DEFAULT NULL,
    UNID_IMOB VARCHAR DEFAULT NULL,
    IDENT_EMP VARCHAR DEFAULT NULL,
    DESC_UNID_IMOB VARCHAR DEFAULT NULL,
    NUM_CONT VARCHAR DEFAULT NULL,
    CPF_CNPJ_ADQU VARCHAR DEFAULT NULL,
    DT_OPER date DEFAULT NULL,
    VL_TOT_VEND DECIMAL(21, 2) DEFAULT NULL,
    VL_REC_ACUM DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_REC DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    PERC_REC_RECEB DECIMAL(8, 2) DEFAULT NULL,
    IND_NAT_EMP TEXT DEFAULT NULL,
    INF_COMP VARCHAR DEFAULT NULL
);

--
-- Registro: f205
--
CREATE TABLE reg_f205 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_CUS_INC_ACUM_ANT DECIMAL(21, 2) DEFAULT NULL,
    VL_CUS_INC_PER_ESC DECIMAL(21, 2) DEFAULT NULL,
    VL_CUS_INC_ACUM DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC_BC_CUS_INC_ACUM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CUS_INC DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_CRED_PIS_ACUM DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_PIS_DESC_ANT DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_PIS_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_PIS_DESC_FUT DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_CRED_COFINS_ACUM DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_COFINS_DESC_ANT DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_COFINS_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_COFINS_DESC_FUT DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: f210
--
CREATE TABLE reg_f210 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_CUS_ORC DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC DECIMAL(21, 2) DEFAULT NULL,
    VL_CUS_ORC_AJU DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CRED DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_CRED_PIS_UTIL DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_CRED_COFINS_UTIL DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: f211
--
CREATE TABLE reg_f211 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f500
--
CREATE TABLE reg_f500 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_REC_CAIXA DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_DESC_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_DESC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    INFO_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: f509
--
CREATE TABLE reg_f509 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f510
--
CREATE TABLE reg_f510 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_REC_CAIXA DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_DESC_PIS DECIMAL(21, 2) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_DESC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    INFO_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: f519
--
CREATE TABLE reg_f519 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f525
--
CREATE TABLE reg_f525 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_REC DECIMAL(21, 2) DEFAULT NULL,
    IND_REC VARCHAR DEFAULT NULL,
    CNPJ_CPF VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    COD_ITEM VARCHAR DEFAULT NULL,
    VL_REC_DET DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    INFO_COMPL VARCHAR DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL
);

--
-- Registro: f550
--
CREATE TABLE reg_f550 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_REC_COMP DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_DESC_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_DESC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    INFO_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: f559
--
CREATE TABLE reg_f559 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f560
--
CREATE TABLE reg_f560 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_REC_COMP DECIMAL(21, 2) DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_DESC_PIS DECIMAL(21, 2) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(12, 4) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_DESC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(12, 4) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    COD_MOD VARCHAR DEFAULT NULL,
    CFOP TEXT DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    INFO_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: f569
--
CREATE TABLE reg_f569 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: f600
--
CREATE TABLE reg_f600 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_NAT_RET VARCHAR DEFAULT NULL,
    DT_RET date DEFAULT NULL,
    VL_BC_RET DECIMAL(23, 4) DEFAULT NULL,
    VL_RET DECIMAL(21, 2) DEFAULT NULL,
    COD_REC TEXT DEFAULT NULL,
    IND_NAT_REC TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL,
    VL_RET_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_RET_COFINS DECIMAL(21, 2) DEFAULT NULL,
    IND_DEC TEXT DEFAULT NULL
);

--
-- Registro: f700
--
CREATE TABLE reg_f700 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_ORI_DED VARCHAR DEFAULT NULL,
    IND_NAT_DED TEXT DEFAULT NULL,
    VL_DED_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_DED_COFINS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_OPER DECIMAL(21, 2) DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL,
    INF_COMP VARCHAR DEFAULT NULL
);

--
-- Registro: f800
--
CREATE TABLE reg_f800 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_NAT_EVEN VARCHAR DEFAULT NULL,
    DT_EVEN date DEFAULT NULL,
    CNPJ_SUCED VARCHAR DEFAULT NULL,
    PA_CONT_CRED VARCHAR DEFAULT NULL,
    COD_CRED VARCHAR DEFAULT NULL,
    VL_CRED_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_COFINS DECIMAL(21, 2) DEFAULT NULL,
    PER_CRED_CIS DECIMAL(8, 2) DEFAULT NULL
);

--
-- Registro: f990
--
CREATE TABLE reg_f990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_F VARCHAR DEFAULT NULL
);

--
-- Registro: i001
--
CREATE TABLE reg_i001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: i010
--
CREATE TABLE reg_i010 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL,
    IND_ATIV VARCHAR DEFAULT NULL,
    INFO_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: i100
--
CREATE TABLE reg_i100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_REC_FIN DECIMAL(21, 2) DEFAULT NULL,
    CST VARCHAR DEFAULT NULL,
    VL_TOT_DED_GER DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_DED_ESP DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(10, 2) DEFAULT NULL,
    VL_PIS DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(10, 2) DEFAULT NULL,
    VL_COFINS DECIMAL(21, 2) DEFAULT NULL,
    INF_COMP VARCHAR DEFAULT NULL
);

--
-- Registro: i199
--
CREATE TABLE reg_i199 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: i200
--
CREATE TABLE reg_i200 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_CAMPO VARCHAR DEFAULT NULL,
    COD_DET VARCHAR DEFAULT NULL,
    VL_DET DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    INF_COMP VARCHAR DEFAULT NULL
);

--
-- Registro: i299
--
CREATE TABLE reg_i299 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: i300
--
CREATE TABLE reg_i300 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_COMP VARCHAR DEFAULT NULL,
    VL_COMP DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    INF_COMP VARCHAR DEFAULT NULL
);

--
-- Registro: i399
--
CREATE TABLE reg_i399 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: i990
--
CREATE TABLE reg_i990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_I VARCHAR DEFAULT NULL
);

--
-- Registro: m001
--
CREATE TABLE reg_m001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: m100
--
CREATE TABLE reg_m100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CRED VARCHAR DEFAULT NULL,
    IND_CRED_ORI TEXT DEFAULT NULL,
    VL_BC_CRED DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_CRED DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_ACRES DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_REDUC DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_DIF DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_DISP DECIMAL(21, 2) DEFAULT NULL,
    IND_DESC_CRED TEXT DEFAULT NULL,
    VL_CRED_DESC DECIMAL(21, 2) DEFAULT NULL,
    SLD_CRED DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m105
--
CREATE TABLE reg_m105 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_BC_PIS_TOT DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS_CUM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS_NC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_PIS DECIMAL(21, 2) DEFAULT NULL,
    QUANT_BC_PIS_TOT DECIMAL(22, 3) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    DESC_CRED VARCHAR DEFAULT NULL
);

--
-- Registro: m110
--
CREATE TABLE reg_m110 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_AJ TEXT DEFAULT NULL,
    VL_AJ DECIMAL(21, 2) DEFAULT NULL,
    COD_AJ VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DESCR_AJ VARCHAR DEFAULT NULL,
    DT_REF date DEFAULT NULL
);

--
-- Registro: m200
--
CREATE TABLE reg_m200 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_TOT_CONT_NC_PER DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CRED_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CRED_DESC_ANT DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CONT_NC_DEV DECIMAL(21, 2) DEFAULT NULL,
    VL_RET_NC DECIMAL(21, 2) DEFAULT NULL,
    VL_OUT_DED_NC DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_NC_REC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CONT_CUM_PER DECIMAL(21, 2) DEFAULT NULL,
    VL_RET_CUM DECIMAL(21, 2) DEFAULT NULL,
    VL_OUT_DED_CUM DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_CUM_REC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CONT_REC DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m205
--
CREATE TABLE reg_m205 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_CAMPO VARCHAR DEFAULT NULL,
    COD_REC VARCHAR DEFAULT NULL,
    VL_DEBITO DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m210
--
CREATE TABLE reg_m210 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CONT VARCHAR DEFAULT NULL,
    VL_REC_BRT DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CONT DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_PIS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_PIS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_CONT_APUR DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_ACRES DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_REDUC DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIFER DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIFER_ANT DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_PER DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m211
--
CREATE TABLE reg_m211 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_TIP_COOP VARCHAR DEFAULT NULL,
    VL_BC_CONT_ANT_EXC_COOP DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC_COOP_GER DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC_ESP_COOP DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CONT DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m220
--
CREATE TABLE reg_m220 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_AJ TEXT DEFAULT NULL,
    VL_AJ DECIMAL(21, 2) DEFAULT NULL,
    COD_AJ VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DESCR_AJ VARCHAR DEFAULT NULL,
    DT_REF date DEFAULT NULL
);

--
-- Registro: m230
--
CREATE TABLE reg_m230 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL,
    VL_VEND DECIMAL(21, 2) DEFAULT NULL,
    VL_NAO_RECEB DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIF DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_DIF DECIMAL(21, 2) DEFAULT NULL,
    COD_CRED VARCHAR DEFAULT NULL
);

--
-- Registro: m300
--
CREATE TABLE reg_m300 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CONT VARCHAR DEFAULT NULL,
    VL_CONT_APUR_DIFER DECIMAL(21, 2) DEFAULT NULL,
    NAT_CRED_DESC VARCHAR DEFAULT NULL,
    VL_CRED_DESC_DIFER DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIFER_ANT DECIMAL(21, 2) DEFAULT NULL,
    PER_APUR VARCHAR DEFAULT NULL,
    DT_RECEB date DEFAULT NULL
);

--
-- Registro: m350
--
CREATE TABLE reg_m350 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_TOT_FOL DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC_BC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_BC DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_PIS_FOL DECIMAL(8, 2) DEFAULT NULL,
    VL_TOT_CONT_FOL DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m400
--
CREATE TABLE reg_m400 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_PIS VARCHAR DEFAULT NULL,
    VL_TOT_REC DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    DESC_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: m410
--
CREATE TABLE reg_m410 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NAT_REC VARCHAR DEFAULT NULL,
    VL_REC DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    DESC_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: m500
--
CREATE TABLE reg_m500 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CRED VARCHAR DEFAULT NULL,
    IND_CRED_ORI TEXT DEFAULT NULL,
    VL_BC_CRED DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_CRED DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_ACRES DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_REDUC DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_DIF DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_DISP DECIMAL(21, 2) DEFAULT NULL,
    IND_DESC_CRED TEXT DEFAULT NULL,
    VL_CRED_DESC DECIMAL(21, 2) DEFAULT NULL,
    SLD_CRED DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m505
--
CREATE TABLE reg_m505 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NAT_BC_CRED VARCHAR DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_BC_COFINS_TOT DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS_CUM DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS_NC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_COFINS DECIMAL(21, 2) DEFAULT NULL,
    QUANT_BC_COFINS_TOT DECIMAL(22, 3) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    DESC_CRED VARCHAR DEFAULT NULL
);

--
-- Registro: m510
--
CREATE TABLE reg_m510 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_AJ TEXT DEFAULT NULL,
    VL_AJ DECIMAL(21, 2) DEFAULT NULL,
    COD_AJ VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DESCR_AJ VARCHAR DEFAULT NULL,
    DT_REF date DEFAULT NULL
);

--
-- Registro: m600
--
CREATE TABLE reg_m600 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    VL_TOT_CONT_NC_PER DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CRED_DESC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CRED_DESC_ANT DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CONT_NC_DEV DECIMAL(21, 2) DEFAULT NULL,
    VL_RET_NC DECIMAL(21, 2) DEFAULT NULL,
    VL_OUT_DED_NC DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_NC_REC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CONT_CUM_PER DECIMAL(21, 2) DEFAULT NULL,
    VL_RET_CUM DECIMAL(21, 2) DEFAULT NULL,
    VL_OUT_DED_CUM DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_CUM_REC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CONT_REC DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m605
--
CREATE TABLE reg_m605 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_CAMPO VARCHAR DEFAULT NULL,
    COD_REC VARCHAR DEFAULT NULL,
    VL_DEBITO DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m610
--
CREATE TABLE reg_m610 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CONT VARCHAR DEFAULT NULL,
    VL_REC_BRT DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CONT DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_COFINS DECIMAL(12, 4) DEFAULT NULL,
    QUANT_BC_COFINS DECIMAL(22, 3) DEFAULT NULL,
    ALIQ_COFINS_QUANT DECIMAL(23, 4) DEFAULT NULL,
    VL_CONT_APUR DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_ACRES DECIMAL(21, 2) DEFAULT NULL,
    VL_AJUS_REDUC DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIFER DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIFER_ANT DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_PER DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m611
--
CREATE TABLE reg_m611 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_TIP_COOP VARCHAR DEFAULT NULL,
    VL_BC_CONT_ANT_EXC_COOP DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC_COOP_GER DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC_ESP_COOP DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CONT DECIMAL(21, 2) DEFAULT NULL
);

--
-- Registro: m620
--
CREATE TABLE reg_m620 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_AJ TEXT DEFAULT NULL,
    VL_AJ DECIMAL(21, 2) DEFAULT NULL,
    COD_AJ VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DESCR_AJ VARCHAR DEFAULT NULL,
    DT_REF date DEFAULT NULL
);

--
-- Registro: m630
--
CREATE TABLE reg_m630 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL,
    VL_VEND DECIMAL(21, 2) DEFAULT NULL,
    VL_NAO_RECEB DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIF DECIMAL(21, 2) DEFAULT NULL,
    VL_CRED_DIF DECIMAL(21, 2) DEFAULT NULL,
    COD_CRED VARCHAR DEFAULT NULL
);

--
-- Registro: m700
--
CREATE TABLE reg_m700 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    COD_CONT VARCHAR DEFAULT NULL,
    VL_CONT_APUR_DIFER DECIMAL(21, 2) DEFAULT NULL,
    NAT_BC_CRED_DESC VARCHAR DEFAULT NULL,
    VL_CRED_DESC_DIFER DECIMAL(21, 2) DEFAULT NULL,
    VL_CONT_DIFER_ANT DECIMAL(21, 2) DEFAULT NULL,
    PER_APUR VARCHAR DEFAULT NULL,
    DT_RECEB date DEFAULT NULL
);

--
-- Registro: m800
--
CREATE TABLE reg_m800 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CST_COFINS VARCHAR DEFAULT NULL,
    VL_TOT_REC DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    DESC_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: m810
--
CREATE TABLE reg_m810 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NAT_REC VARCHAR DEFAULT NULL,
    VL_REC DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    DESC_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: m990
--
CREATE TABLE reg_m990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_M VARCHAR DEFAULT NULL
);

--
-- Registro: p001
--
CREATE TABLE reg_p001 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_MOV TEXT DEFAULT NULL
);

--
-- Registro: p010
--
CREATE TABLE reg_p010 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    CNPJ VARCHAR DEFAULT NULL
);

--
-- Registro: p100
--
CREATE TABLE reg_p100 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    DT_INI date DEFAULT NULL,
    DT_FIM date DEFAULT NULL,
    VL_REC_TOT_EST DECIMAL(21, 2) DEFAULT NULL,
    COD_ATIV_ECON VARCHAR DEFAULT NULL,
    VL_REC_ATIV_ESTAB DECIMAL(21, 2) DEFAULT NULL,
    VL_EXC DECIMAL(21, 2) DEFAULT NULL,
    VL_BC_CONT DECIMAL(21, 2) DEFAULT NULL,
    ALIQ_CONT DECIMAL(12, 4) DEFAULT NULL,
    VL_CONT_APU DECIMAL(21, 2) DEFAULT NULL,
    COD_CTA VARCHAR DEFAULT NULL,
    INFO_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: p110
--
CREATE TABLE reg_p110 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_CAMPO VARCHAR DEFAULT NULL,
    COD_DET VARCHAR DEFAULT NULL,
    DET_VALOR DECIMAL(21, 2) DEFAULT NULL,
    INF_COMPL VARCHAR DEFAULT NULL
);

--
-- Registro: p199
--
CREATE TABLE reg_p199 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    NUM_PROC VARCHAR DEFAULT NULL,
    IND_PROC TEXT DEFAULT NULL
);

--
-- Registro: p200
--
CREATE TABLE reg_p200 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    PER_REF VARCHAR DEFAULT NULL,
    VL_TOT_CONT_APU DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_AJ_REDUC DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_AJ_ACRES DECIMAL(21, 2) DEFAULT NULL,
    VL_TOT_CONT_DEV DECIMAL(21, 2) DEFAULT NULL,
    COD_REC VARCHAR DEFAULT NULL
);

--
-- Registro: p210
--
CREATE TABLE reg_p210 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    IND_AJ TEXT DEFAULT NULL,
    VL_AJ DECIMAL(21, 2) DEFAULT NULL,
    COD_AJ VARCHAR DEFAULT NULL,
    NUM_DOC VARCHAR DEFAULT NULL,
    DESCR_AJ VARCHAR DEFAULT NULL,
    DT_REF date DEFAULT NULL
);

--
-- Registro: p990
--
CREATE TABLE reg_p990 (
    ID INTEGER PRIMARY KEY,
    PARENT_ID INTEGER DEFAULT NULL,
    REG TEXT DEFAULT NULL,
    QTD_LIN_P VARCHAR DEFAULT NULL
);
