// @generated automatically by Diesel CLI.

diesel::table! {
    efd_c100 (id) {
        id -> Integer,
        file_id -> Nullable<Integer>,
        parent_id -> Nullable<Integer>,
        reg -> Nullable<Text>,
        ind_oper -> Nullable<Text>,
        ind_emit -> Nullable<Text>,
        cod_part -> Nullable<Text>,
        cod_mod -> Nullable<Text>,
        cod_sit -> Nullable<Text>,
        ser -> Nullable<Text>,
        num_doc -> Nullable<Text>,
        chv_nfe -> Nullable<Text>,
        dt_doc -> Nullable<Text>,
        dt_e_s -> Nullable<Text>,
        vl_doc -> Nullable<Text>,
        ind_pgto -> Nullable<Text>,
        vl_desc -> Nullable<Text>,
        vl_abat_nt -> Nullable<Text>,
        vl_merc -> Nullable<Text>,
        ind_frt -> Nullable<Text>,
        vl_frt -> Nullable<Text>,
        vl_seg -> Nullable<Text>,
        vl_out_da -> Nullable<Text>,
        vl_bc_icms -> Nullable<Text>,
        vl_icms -> Nullable<Text>,
        vl_bc_icms_st -> Nullable<Text>,
        vl_icms_st -> Nullable<Text>,
        vl_ipi -> Nullable<Text>,
        vl_pis -> Nullable<Text>,
        vl_cofins -> Nullable<Text>,
        vl_pis_st -> Nullable<Text>,
        vl_cofins_st -> Nullable<Text>,
    }
}
