// @generated automatically by Diesel CLI.

diesel::table! {
    reg_c170 (id) {
        id -> Integer,
        file_id -> Nullable<Integer>,
        parent_id -> Nullable<Integer>,
        reg -> Nullable<Text>,
        num_item -> Nullable<Text>,
        cod_item -> Nullable<Text>,
        descr_compl -> Nullable<Text>,
        qtd -> Nullable<Text>,
        unid -> Nullable<Text>,
        vl_item -> Nullable<Text>,
        vl_desc -> Nullable<Text>,
        ind_mov -> Nullable<Text>,
        cst_icms -> Nullable<Text>,
        cfop -> Nullable<Text>,
        cod_nat -> Nullable<Text>,
        vl_bc_icms -> Nullable<Text>,
        aliq_icms -> Nullable<Text>,
        vl_icms -> Nullable<Text>,
        vl_bc_icms_st -> Nullable<Text>,
        aliq_st -> Nullable<Text>,
        vl_icms_st -> Nullable<Text>,
        ind_apur -> Nullable<Text>,
        cst_ipi -> Nullable<Text>,
        cod_enq -> Nullable<Text>,
        vl_bc_ipi -> Nullable<Text>,
        aliq_ipi -> Nullable<Text>,
        vl_ipi -> Nullable<Text>,
        cst_pis -> Nullable<Text>,
        vl_bc_pis -> Nullable<Text>,
        aliq_pis_perc -> Nullable<Text>,
        quant_bc_pis -> Nullable<Text>,
        aliq_pis_reais -> Nullable<Text>,
        vl_pis -> Nullable<Text>,
        cst_cofins -> Nullable<Text>,
        vl_bc_cofins -> Nullable<Text>,
        aliq_cofins_perc -> Nullable<Text>,
        quant_bc_cofins -> Nullable<Text>,
        aliq_cofins_reais -> Nullable<Text>,
        vl_cofins -> Nullable<Text>,
        cod_cta -> Nullable<Text>,
    }
}
